---
title: "DAGs"
author: "Tyler Beaman"
format: pdf
editor: visual
---

## Simple Dag

```{r}
#loading neccesary packages
#install.packages("ggdag")
library(ggdag)
library(dagitty)
library(ggplot2)
```

```{r}
#this is the DAG that represents the data we will use for answering the question
#code is from daggity

Simple_Dag <- dagitty('
dag {
  bb="0,0,1,1"
  "No Calf" [pos="0.484,0.041"]
  Behavior [outcome,pos="0.339,0.195"]
  Calf [pos="0.208,0.048"]
  "No Calf" -> Behavior
  Calf -> Behavior
}
')


plot(Simple_Dag)

```

## Complex Dag
```{r}
#this is the code for the more complex dag

Complex_Dag <- dagitty ('dag {
bb="0,0,1,1"
"Food Availability" [pos="0.630,0.478"]
"Food Source Population" [pos="0.679,0.342"]
"Human Presence" [pos="0.474,0.562"]
"Ice Coverage" [pos="0.742,0.435"]
"No Calf" [pos="0.575,0.156"]
"Presence of Other Whales" [pos="0.190,0.412"]
Age [pos="0.433,0.139"]
Behavior [pos="0.438,0.341"]
Calf [pos="0.261,0.172"]
Gender [pos="0.667,0.263"]
Predators [pos="0.297,0.586"]
"Food Availability" -> Behavior
"Food Source Population" -> "Food Availability"
"Food Source Population" -> Behavior
"Human Presence" -> "Food Availability"
"Human Presence" -> Behavior
"Human Presence" <-> Predators
"Ice Coverage" -> "Food Availability"
"Ice Coverage" -> Behavior
"No Calf" -> Behavior
"Presence of Other Whales" -> "Food Availability"
"Presence of Other Whales" -> "Human Presence"
"Presence of Other Whales" -> Behavior
"Presence of Other Whales" -> Predators
Age -> "No Calf"
Age -> "Presence of Other Whales"
Age -> Behavior
Age -> Calf
Calf -> "Presence of Other Whales"
Calf -> Behavior
Calf -> Predators
Gender -> "No Calf"
Gender -> Behavior
Gender -> Calf
Predators -> Behavior
}')

plot(Complex_Dag)
```
